var suggestions = [
    "为什么我的",
    "面膜",
    "人生好难",
    "为什么我没有工作了",
    "为什么我的世界",
    "尼玛",
    "Amazon distorys the world",
    "A Diamond is Forever",
    "America runs on Dunkin",
    "America produces Covid",
    "Airbnb doesn't let me book",
    "Airbnb doesn't allow parties",
    "A Bidding War Breaks Out During Scrub Dadd's Pitch",
    "Adidas promo code expires",
    "Adele one night only",
    "BMW spreads hidden secrets",
    "Burberry removes the bad news",
    "Bad boy perfume",
    "Becuase You're Worth it",
    "Can You Hear Me Now?",
    "Can You Feel the Love Tonight",
    "Can you run it",
    "Can you Feel My World",
    "Can you get booster if you have covid",    
    "Don't do it",
    "You Got this",
    "Don't search Hao on Internet",
    "Don't buy art",
    "Don't you love me?",
    "Don't you know that this search box is",
    "Don't look up",
    "Don't look back in anger",
    "Don't look away",
    "Don't look at screen",
    "Deleted information",
    "Deleted ID",
    "Egg benedict calories",
    "English Muffin is made in italy",
    "Evil Speed Force",
    "Endless Summer Maddess",
    "Elite",
    "Explained: What's life",
    "Evil Twin makes Hao happy",
    "Evagelion is Hao's favorite Anmiation",
    "Facebook hidden timeline",
    "Facebook needs your attention",
    "Facebook needs your body",
    "Facebook moves your eyeball",
    "Facebook tells twitter a joke",
    "Friends' last epsisode",
    "Facebook hidden post",
    "Face mask",
    "Face Off",
    "Fake news generator",
    "Fumat - All The Way/Massane",
    "Faster(Vocal Synthwave + Retrowave)",
    "Face Eater",
    "Gu Ailin is a girl",
    "Google doesn't suppose Hao",
    "Google hates free speech",
    "Google hates christmas",
    "Google love songs",
    "Google isn't available here",
    "Gucci is better",
    "Guacamole is made of guava",
    "Guava makes you fat",
    "Gorgon City B2b John Summit",
    "Hi, Hao",
    "Hey Hao",
    "Hello Hao",
    "Hao is the best artist",
    "Hao loves New York Strip",
    "Hao universe is made of this",
    "How one of New York's Best Chocolate Factories Makes 500....",
    "Hao isn't rich yet",
    "I made A 24K Gold Brisket (ft.Guga Foods)",
    "Mashmello - Here With Me Feat CHVRCHES",
    "The BBQ King of Brooklyn|Street Food Icons",
    "The Midnight - Last Train (Sleeping by the Waves Remix)",
    "A popular Chinese chef who works 20 hours a day for 40 years",
    "Fast Food Done Right with Hao Ramsay",
    "Fast Food make you fit",
    "The Techniques That Gave AKIRA Its Unprecedented Quality",
    "Back to you",
    "Shallou - High Tide(Fan-Made Nomad Seires)",
    "How to Make Churros With Caramel Sauce",
    "How Spider-Man No Way Home Should Have Ended",
    "You Season 4",
    "Lane 8 - Sunrise set",
    "Justin Bieber - Somebody",
    "Think Different",
    "The Bigger the better",
    "Open Happiness",
    "Where's the Beef?",
    "Melts in Your Mouth",
    "The Breakfast of Champions",
    "How I Met Your Mother",
    "How to get Rich",
    "How are you doing",
    "Iron Cast Steak",
    "I love you with my Balls",
    "Instagram is supposed to be friendly",
    "IKEA stock isn't available because of ",
    "Issue free Internet",
    "Internet will be free",
    'Jojo Adventure',
    'In what order do I watch Jojo',
    'KFC isn\'t advertising chicken tenders because of',
    "KIEHL'S could contain phenoxyethanol",
    "Keep losing myself",
    "Keep telling yourself you are special",
    "Louis Vuitton Never Has a Sale!",
    "Luxury is a lifestyle",
    "Luxury is a state of mind",
    "LOL",
    "Money moves your body",
    "Money Massage your mind",
    "Massage Center",
    "Nike loves sneaker bot",
    "Netflix bought by Facebook",
    "OpenSea isn't an ocean",
    "Omicron varaints",
    "Overwatch",
    "You are a TANK",
    "Petter pan grow up",
    "I GOT TIME",
    "Time is valuable. I prefer to waste it",
    "BOOM",
    "I'M PAN SEXUAL",
    "HMMMMMM...",
    "Before it was CRUEL",
    "Pig",
    "My Dad",
    "Beauty Queen Expert",
    "Oh GOD",
    "Power of People. Tesla.",
    "Thank You. My Darling",
    "Thank you for use my service",
    "Protend to be rich",
    "My new hoppy is to sleep",
    "I got a new roomate",
    "My roomate is stupid",
    "Why I have a roomate",
    "Toyota owner is whatever",
    "Tesla is cool",
    "Queen B",
    "You are mentioned",
    "Questions.",
    "I'm not seeing anything",
    "That's a good question",
    "TO STUDY, OR NOT TO STUDY",
    "Sister",
    "When you lecturer askes you some questions....",
    "Do You Have a Question",
    "Any Questions. Please no",
    "Reading the first question on a test",
    "Great Question",
    "That is the question",
    "SO.... Let ME ASK YOU A QUESTION",
    "I MUSTACHE YOU A QUESTION",
    "University",
    "We are gonna be famous",
    "Why have I made any friends at uni?",
    "I have no idea what I'm doing",
    "When someone asks me how did I survive the last semester",
    "And What",
    "When professors assign their own articles as readings",
    "All you need is motivation",
    "Realize you have done nothing all semster",
    "Not focused",
    "Open up by a wrong person",
    "I'll be fun they said",
    "Zoom meeting",
    "Me and the boys ready for Zoom",
    "The Entire class in the zoom call",
    "Everyone please turn on your camera",
    "Mute yourself",
    "Don't ask me. Ask Google.",
    "Ask Google",
    "The guests are gone",
    "Follow your heart",
    "me looking at myslef in the video chat",
    "Another Zoom Meeting?",
    "I got a new Pokemon",
    "Ask Twitter",
    "Twitter doesn't know",
    "You know Twitter doesn't know",
    "You know Google doesn't know",
    "Google knows",
    "Zooma Zoom Zoom Zoom in the Boom Boom",
    "Puonners of Zoom",
    "Me..",
    "I was like..",
    "The final boss once you've defeated",
    "Dick",
    "Hao Loves art",
    "Youtube",
    "Trying to tell your coworker my pants",
    "Money",
    "Power",
    "Car",
    "Real Estate",
    "Migration",
    "Nothing Less",
    "Truth",
    "Life",
    "Meaning",
    "Car",
    "Vehicle",
    "Crash"
]