var suggestions = [
    "为什么我的",
    "面膜",
    "人生好难",
    "为什么我没有工作了",
    "为什么我的世界",
    "尼玛",
    "Amazon distorys the world",
    "A Diamond is Forever",
    "America runs on Dunkin",
    "America produces Covid",
    "Airbnb doesn't let me book",
    "Airbnb doesn't allow parties",
    "A Bidding War Breaks Out During Scrub Dadd's Pitch",
    "Adidas promo code expires",
    "Adele one night only",
    "BMW spreads hidden secrets",
    "Burberry removes the bad news",
    "Bad boy perfume",
    "Becuase You're Worth it",
    "Can You Hear Me Now?",
    "Can You Feel the Love Tonight",
    "Can you run it",
    "Can you Feel My World",
    "Can you get booster if you have covid",    
    "Don't do it",
    "You Got this",
    "Don't search Hao on Internet",
    "Don't buy art",
    "Don't you love me?",
    "Don't you know that this search box is",
    "Don't look up",
    "Don't look back in anger",
    "Don't look away",
    "Don't look at screen",
    "Deleted information",
    "Deleted ID",
    "Egg benedict calories",
    "English Muffin is made in italy",
    "Evil Speed Force",
    "Endless Summer Maddess",
    "Elite",
    "Explained: What's life",
    "Evil Twin makes Hao happy",
    "Evagelion is Hao's favorite Anmiation",
    "Facebook hidden timeline",
    "Facebook needs your attention",
    "Facebook needs your body",
    "Facebook moves your eyeball",
    "Facebook tells twitter a joke",
    "Friends' last epsisode",
    "Facebook hidden post",
    "Face mask",
    "Face Off",
    "Fake news generator",
    "Fumat - All The Way/Massane",
    "Faster(Vocal Synthwave + Retrowave)",
    "Face Eater",
    "Gu Ailin is a girl",
    "Google doesn't suppose Hao",
    "Google hates free speech",
    "Google hates christmas",
    "Google love songs",
    "Google isn't available here",
    "Gucci is better",
    "Guacamole is made of guava",
    "Guava makes you fat",
    "Gorgon City B2b John Summit",
    "Hi, Hao",
    "Hey Hao",
    "Hello Hao",
    "Hao is the best artist",
    "Hao loves New York Strip",
    "Hao universe is made of this",
    "How one of New York's Best Chocolate Factories Makes 500....",
    "Hao isn't rich yet",
    "I made A 24K Gold Brisket (ft.Guga Foods)",
    "Mashmello - Here With Me Feat CHVRCHES",
    "The BBQ King of Brooklyn|Street Food Icons",
    "The Midnight - Last Train (Sleeping by the Waves Remix)",
    "A popular Chinese chef who works 20 hours a day for 40 years",
    "Fast Food Done Right with Hao Ramsay",
    "Fast Food make you fit",
    "The Techniques That Gave AKIRA Its Unprecedented Quality",
    "Back to you",
    "Shallou - High Tide(Fan-Made Nomad Seires)",
    "How to Make Churros With Caramel Sauce",
    "How Spider-Man No Way Home Should Have Ended",
    "You Season 4",
    "Lane 8 - Sunrise set",
    "Justin Bieber - Somebody",
    "Think Different",
    "The Bigger the better",
    "Open Happiness",
    "Where's the Beef?",
    "Melts in Your Mouth",
    "The Breakfast of Champions",
    

    "Dick",
    "Hao Loves art",
    "Youtube",
    "Money",
    "Power",
    "Car",
    "Real Estate",
    "Migration",
    "Nothing Less",
    "Truth",
    "Life",
    "Meaning",
    "Car",
    "Vehicle",
    "Crash"
]