let newsTitle=['prada','郑爽与姚安娜：“贵圈”意难平"',
               'prada','菜市场沦为“网红垃圾场”，拍照后把菜扔掉：烟火气的生活不在了？',
               'burberry','#江汉路步行街#',
               'burberry','Burning unsold goods and using real fur',
               'burberry','Burns bags,clothes and perfume worth millions',
               'kiehls','河南一男子找老婆借护肤品',
               'QQ','为女朋友织围巾的男生他不帅吗？',
               'IKEA','Nearly fainted',
               'IKEA','Memory Foam and Night Sweats',
               'Apple','Why does my voice sound like a Robot on Phone Calls',
               'Chanel','My Boy Bag',
               'Chanel','以生日为借口一定要拿下',
               'Chanel','上次没涨价都涨了',
               'Louis Vuitton','都是赚个红包钱',
               'Louis Vuitton','Price Hike',
               'Louis Vuitton','Line Up',
               'Lous Vuitton','Have a good day',
               'Blue Frog Restaurant','感觉整个人从头到脚都焕然一新了',
               'covid','室友都很开心 我反而觉得难过',
               'panada','我又觉着我可以了',
               'Dior','Has gone vegan!',
               'Nike',"The Beginner's guide to Sneaker Botting",
               'Adidas','11 Best Sneaker Bots in 2022',
               'KFC','知道今天是什么日子吗',
               'KFC','我怕我走不出上段感情。但是我不小心打开微信小程序时发现今天',
               'KFC','劝大家别买iPhone13，这样能省下好几千',
               'Mcdonald','香菜',
               'Chase','像一个粉色的Tom Ford',
               'BANK','浪漫的夏季 还有施华洛世奇',
               'BANK','找一个Gucci的角落',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','',
               '','']


               
               
               
               
               
               
               
               
               


